name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main ブランチに push された時にデプロイ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # npm install で依存関係をインストール
      - name: Install dependencies
        run: npm install

      # npm run build を実行
      - name: Run build
        run: npm run build  # ダミーで 'No build step required' と表示

      # GitHub Pages 用にファイルをアップロード
      - name: Deploy to GitHub Pages
        run: npm run deploy  # gh-pages を使ってデプロイ
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token
